apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: java-springboot-jivmrbtc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot-jivmrbtc 
  name: java-springboot-jivmrbtc
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: java-springboot-jivmrbtc 
